[project]
name = "mist460-course-recommender-kenney"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.119.0",
    "pyodbc>=5.3.0",
    "uvicorn>=0.37.0",
]
